version: '3'
services:
    web:
        restart: always
        image: nginx:1.14.0-alpine
        volumes:
          - ./test_app.conf:/etc/nginx/conf.d/default.conf
          - ../:/src
        ports:
        - "8080:80"
        networks:
          - internal
    php:
        restart: always
        build:
          context: ./
          dockerfile: Dockerfile
        volumes:
          - ../:/src
        networks:
          - internal
        expose:
          - "9000"
    mysql:
        restart: always
        image: mysql:5.7
        expose:
          - "3306"
        ports:
          - "5306:3306"
        volumes:
          - mysql-data:/var/lib/mysql
        networks:
          - internal
        environment:
            MYSQL_DATABASE: test_app
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        labels:
          - traefik.enable=false

volumes:
    mysql-data:

networks:
  internal:
    external: false
